#!/usr/bin/env python3

from pptx import Presentation
from pptx.util import Inches
from pptx.util import Mm
from pptx.util import Pt
from pypdf import PdfReader

pdf_reader = PdfReader('demo/demo.pdf')
pdf_box = pdf_reader.pages[0].mediabox
slide_width, slide_height = pdf_box[2], pdf_box[3]

prs = Presentation()
prs.slide_width = Pt(slide_width)
prs.slide_height = Pt(slide_height)
blank_slide_layout = prs.slide_layouts[6]

for i in range(3):
    slide = prs.slides.add_slide(blank_slide_layout)

    emf_path = f'demo/_svg.tmp/demo_{i+1}.emf'
    pic = slide.shapes.add_picture(emf_path, Inches(0), Inches(0), width=prs.slide_width)

prs.save('demo/demo.pptx')
